/*
Version 1.0, 30-12-2007, First release

IMPORTANT NOTICE, please read:

This software is licensed under the terms of the GNU GENERAL PUBLIC LICENSE,
please read the enclosed file license.txt or http://www.gnu.org/licenses/licenses.html

Note that this software is freeware and it is not designed, licensed or intended
for use in mission critical, life support and military purposes.

The use of this software is at the risk of the user.
*/

/* 

class Preference provides the preferences

javalc6
*/
package visualap;
import java.util.*;
import java.io.*;


public class Preference {  
	static final String preferencesFile = "visual.ini";
	String beansDir;

// empty constructor
	public Preference () {  
	}

// readXML()
// read preferences from default file, as defined in preferencesFile
// note that default values will be used if IO failure occurs
	public Preference readXML() {  
		InputStream is;
		try	{
			is = new FileInputStream(new File(preferencesFile));
		}	catch (IOException ex) { is = null;}
		return readXML(is);
	}

// readXML(InputStream is)
// note that default values will be used if IO failure occurs
	public Preference readXML(InputStream is) {  
		Properties props=new Properties();
		if (is != null)
		try	{
			props.loadFromXML(is);
		}	catch (IOException ex) {	}
		beansDir=props.getProperty("beansDir","beans");
		return this;
	}

// writeXML()
	public void writeXML() throws FileNotFoundException, IOException {  
		writeXML(new FileOutputStream(new File(preferencesFile)));
	}

// writeXML(OutputStream os)
	public void writeXML(OutputStream os) throws FileNotFoundException, IOException {  
			Properties props=new Properties();
			props.setProperty("beansDir",beansDir);
			props.storeToXML(os,"generated by VisualAp");
	}

};